"""
Gmail Report Sender
Sends the AI YouTube report via Gmail using OAuth.

Usage: python tools/send_email.py
Requires: Gmail API enabled on your Google Cloud project + client_secret*.json
Input: .tmp/ai_youtube_report.pdf
"""

import base64
import glob
import mimetypes
import sys
from datetime import datetime, timezone
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

ROOT = Path(__file__).resolve().parent.parent
TOKEN_PATH = ROOT / "gmail_token.json"
REPORT_PATH = ROOT / ".tmp" / "ai_youtube_report.pdf"

# Gmail scopes
SCOPES = [
    "https://www.googleapis.com/auth/gmail.send",
    "https://www.googleapis.com/auth/gmail.readonly",
]


def find_client_secret():
    """Find the OAuth client secret JSON file in the project root."""
    for pattern in [str(ROOT / "client_secret*.json"), str(ROOT / "credentials.json")]:
        matches = glob.glob(pattern)
        if matches:
            return matches[0]
    return None


def get_gmail_service():
    """Build Gmail API service with OAuth."""
    client_secret = find_client_secret()
    if not client_secret:
        print("ERROR: No client_secret*.json found in project root.")
        sys.exit(1)

    creds = None
    if TOKEN_PATH.exists():
        creds = Credentials.from_authorized_user_file(str(TOKEN_PATH), SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            print("Refreshing Gmail token...")
            creds.refresh(Request())
        else:
            print("Opening browser for Gmail sign-in...")
            print("(Authorize the app to send emails)")
            flow = InstalledAppFlow.from_client_secrets_file(client_secret, SCOPES)
            creds = flow.run_local_server(port=0)

        with open(TOKEN_PATH, "w") as f:
            f.write(creds.to_json())
        print("Gmail token saved.")

    return build("gmail", "v1", credentials=creds)


def get_user_email(service):
    """Get the authenticated user's email address."""
    profile = service.users().getProfile(userId="me").execute()
    return profile["emailAddress"]


def send_report(service, to_email: str, report_path: Path):
    """Send the report as an email attachment."""
    today = datetime.now(timezone.utc).strftime("%B %d, %Y")

    msg = MIMEMultipart()
    msg["To"] = to_email
    msg["Subject"] = f"AI YouTube Analysis Report — {today}"

    body = f"""Hi,

Here's your weekly AI YouTube Landscape Report for {today}.

Full details in the attached PDF report.

---
Generated by YouTube AI Analysis Automation
"""
    msg.attach(MIMEText(body, "plain"))

    # Attach the PDF file
    with open(report_path, "rb") as f:
        attachment = MIMEBase("application", "pdf")
        attachment.set_payload(f.read())

    from email import encoders
    encoders.encode_base64(attachment)
    attachment.add_header(
        "Content-Disposition", "attachment",
        filename=f"AI_YouTube_Report_{datetime.now().strftime('%Y%m%d')}.pdf"
    )
    msg.attach(attachment)

    # Send
    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    service.users().messages().send(
        userId="me", body={"raw": raw}
    ).execute()

    return to_email


def main():
    if not REPORT_PATH.exists():
        print(f"ERROR: Report not found: {REPORT_PATH}")
        print("Run the PDF builder first: python tools/build_pdf.py")
        sys.exit(1)

    print("Gmail Report Sender")
    print("-" * 50)

    service = get_gmail_service()
    email = get_user_email(service)
    print(f"Authenticated as: {email}")

    print(f"Sending report to {email}...")
    send_report(service, email, REPORT_PATH)
    print(f"Report sent successfully to {email}!")


if __name__ == "__main__":
    main()
